name: EmoRoBERTaNet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pip
  - black
  - python
  - pytorch
  - datasets
  - accelerate
  - torchaudio
  - torchvision
  - scikit-learn
  - transformers
  - huggingface_hub
  - pytorch-cuda=12.1
